# Generated by Django 4.1.1 on 2023-07-16 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskman', '0007_alter_project_contributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='createon',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'IN PROGRESS'), (2, 'IN HOLD'), (3, 'COMPLETED')], default=1),
        ),
    ]
