# Generated by Django 4.1.4 on 2023-07-17 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskman', '0008_project_createon_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='create_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
